function[] = fPlot_mufbx(x_a, the_a, xInterp_a, ...
                y_b2, yInterp_a, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
% scrsz(4) = scrsz(4)*4;
fontS = 56;
MarkerS = 17;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);

colors=zeros(size(colors));
colors(7,:)=[0 0 0];
color_conf =[0 0 0 0.35];
mColorLat = [0. 0. 0.];
lWidth_conf = 40;
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
mStyles_b = {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',3*[1 scrsz(3) scrsz(3)/5 scrsz(3)]);


axes1 = axes('Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.0','1.0','2.0','3.0','4.0','5.0'},...
    'XTick',0.0:1:5,...
    'YTickLabel',{'','0.25','0.50','0.75','1.00','1.25','1.50'},...
    'YTick',0.0:0.25:1.5,...
    'LineWidth', 3);
hold(axes1,'all');
box(axes1,'on');
grid(axes1,'off');

xlim(axes1,[0. 5]);
ylim(axes1,[0. 1.5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(axes1,'Layer','top','Clipping','on','ClippingStyle','rectangle');
legend('off')
%% LAT without Qb (for legend) 

% create plot of mu 2p-lat
plot1(1) = plot(x_a(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' \it S\rm = 0.020');

% create plot of mu 4p-lat
plot1(numel(plot1)+1) = plot(x_a(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' \it S\rm = 0.035');

% create plot of mu 6p-lat
plot1(numel(plot1)+1) = plot(x_a(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' \it S\rm = 0.055');



%% LAT with Qb

% create plot of mu 2p-lat
plot(the_a(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface');

% create plot of mu 4p-lat
plot(the_a(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.035)');

% create plot of mu 6p-lat
plot(the_a(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.055)');

% REGRESSION CURVES
% confidence 
plot(xInterp_a,yInterp_a,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curve 
plot(xInterp_a,yInterp_a,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation subcritical');


% LINE UP
fMakeXgrid(1:1:4,[0,1.5],0.5);
fMakeYgrid([0,5],0.25:0.25:1.25,0.5);

% Create xlabel
xlabel('Relative contraction width\it b_{*}\rm [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
ylabel('Discharge coefficient \mu_{f} [-]',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');  

% create legend here
lgnd = legend(plot1);
set(lgnd,'Location','SouthWest','LineWidth',1);


if write2disc
    cd('figures');
    export_fig mufbx.png -png
    export_fig mufbx.eps -eps
    cd ..
    disp('Figure (mufbx) written to disc (figures folder).');
    close all;
end

