function[] = fPlot_mufhx(x_b, the_b, xInterp_b, ...
                y_b2, yInterp_b, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
% scrsz(4) = scrsz(4)*4;
fontS = 28;
MarkerS = 15;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
I = [0.020433, 0.034772 , 0.055021];
colors=zeros(size(colors));
colors(7,:)=[0 0 0];
color_conf =[0 0 0 0.35];
mColorLat = [0. 0. 0.];
lWidth_conf = 50;
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
mStyles_b = {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.5]);

%% SUBPLOT a) -- vertical
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.25','0.50','0.75','1.00','1.25','1.50'},...
    'YTick',0.0:0.25:1.5,...
    'LineWidth', 3);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 1]);
ylim(subplot1,[0. 1.5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');

%% LAT without Qb (for legend) 

% create plot of mu 2p-lat
plot1(1) = plot(x_b(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.020');

% create plot of mu 4p-lat
plot1(numel(plot1)+1) = plot(x_b(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.035');

% create plot of mu 6p-lat
plot1(numel(plot1)+1) = plot(x_b(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.055');

%lgnd = legend(subplot1,'show','Location','SouthEast');


%% LAT with Qb

% create plot of mu 2p-lat
plot1(numel(plot1)+1) = plot(the_b(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface');

% create plot of mu 4p-lat
plot1(numel(plot1)+1) = plot(the_b(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.035)');

% create plot of mu 6p-lat
plot1(numel(plot1)+1) = plot(the_b(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.055)');

% LINE UP
fMakeXgrid(0.2:0.2:0.8,[0,1.5],0.5);
fMakeYgrid([0,1],0.25:0.25:1.25,0.5);

% Create xlabel
xlabel('Relative upstream water depth h_* [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
ylabel('Discharge coefficient \mu_f [-]',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');  
annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

%% SUBPLOT b) SLOPE CORRECTION
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.00','0.01','0.02','0.03','0.04','0.05'},...
    'XTick',0.0:0.01:0.05,...
    'YTickLabel',{'','0.25','0.50','0.75','1.00','1.25','1.50'},...
    'YTick',0.0:0.25:1.5,...
    'LineWidth', 3);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 0.05]);
ylim(subplot2,[0. 1.5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');

%% LAT without Qb (for legend) 

% create plot of mu 2p-lat
plot2(1) = plot(x_b(:,1)*I(1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.020');

% create plot of mu 4p-lat
plot2(numel(plot1)+1) = plot(x_b(:,2)*I(2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.035');

% create plot of mu 6p-lat
plot2(numel(plot1)+1) = plot(x_b(:,3)*I(3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S = 0.055');

% create legend here
lgnd = legend(subplot2,'show');
set(lgnd,'Location','SouthEast','LineWidth',1);


%% LAT with Qb

% create plot of mu 2p-lat
plot2(numel(plot1)+1) = plot(the_b(:,1)*I(1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface');

% create plot of mu 4p-lat
plot2(numel(plot1)+1) = plot(the_b(:,2)*I(2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.035)');

% create plot of mu 6p-lat
plot2(numel(plot1)+1) = plot(the_b(:,3)*I(3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.055)');

% REGRESSION CURVES
% confidence 
plot2(numel(plot1)+1) = plot(xInterp_b,yInterp_b,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curve 
plot2(numel(plot1)+1) = plot(xInterp_b,yInterp_b,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation subcritical');

% LINE UP
fMakeXgrid(0.01:0.01:0.04,[0,1.5],0.5);
fMakeYgrid([0,0.05],0.25:0.25:1.25,0.5);

% Create xlabel
xlabel('Slope correction h_* \cdot S [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
ylabel('Discharge coefficient \mu_f [-]',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');  

annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

if write2disc
    cd('figures');
    export_fig mufhx.png -png
    export_fig mufhx.eps -eps
    cd ..
    disp('Figure (mufx) written to disc (figures folder).');
    close all;
end

