function[] = fPlot_bxhx(x_a, x_b, the_a, the_b, xInterp_bIx, xInterp_b1, xInterp_b2, ...
            xInterp_b3, yInterp_b1, yInterp_b2, yInterp_b3, y_b, yInterp_bIx, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 34;
MarkerS = 15;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);

colors=zeros(size(colors));
colors(7,:)=[0 0 0];
color_conf =[0 0 0 0.35];%[R B G opac.] opac = 0 --> fully transparent
lWidth_conf = 45;
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);



%% SUBPLOT a) -- vertical
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.0','1.0','2.0','3.0','4.0','5.0'},...
    'XTick',0.0:1:5,...
    'YTickLabel',{'','0.5','1.0','1.5','2.0'},...
    'YTick',0.0:0.5:2,...
    'LineWidth', 3);

hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 5]);
ylim(subplot1,[0. 2]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');
legend('off')
% create plot of hx 2p
plot1(1) = plot(x_a(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.020');

% create plot of hx 4p
plot1(2) = plot(x_a(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.035');
% create plot of hx 6p
plot1(3) = plot(x_a(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.055');


% create plot of hx 2p with bedload
plot(the_a(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName',' S = 0.020');

% create plot of hx 4p with bedload
plot(the_a(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName',' S = 0.035');
% create plot of hx 6p with bedload
plot(the_a(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

%legend boxoff
%set(lgnd,'color','none');
% regression curve - confidence
% plot1(7) = plot(xInterp_a,yInterp_a,...
%     'Color',color_conf,...
%     'LineWidth',lWidth_conf+5,'LineStyle',lStyles{1,2},...
%     'Marker',mStyles{1,4},...
%     'DisplayName',' S = 0.02');
% 
% 
% regression curve 2p
plot(xInterp_b1,yInterp_b1,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');
% regression curve 4p
plot(xInterp_b2,yInterp_b2,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');
% regression curve 6p
plot(xInterp_b3,yInterp_b3,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');

% regression curve - confidence
plot(xInterp_b1,yInterp_b1,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName',' S = 0.020');
% regression curve - confidence
plot(xInterp_b2,yInterp_b2,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-10,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName',' S = 0.035');
% regression curve - confidence
plot(xInterp_b3,yInterp_b3,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-20,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName',' S = 0.055');

fMakeXgrid(1:1:4,[0,2],0.5);
fMakeYgrid([0,5],0.5:0.5:2,0.5);

% Create xlabel
xlabel('Relative contraction width\it b_{*}\rm [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
ylabel('Relative upstream water depth\it h_{*}\rm [-]',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');
annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');
% create legend here
lgnd = legend(plot1);
set(lgnd,'Location','SouthEast','LineWidth',1);
%% SUBPLOT b) -- lateral
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.00','0.05','0.10','0.15','0.20','0.25'},...
    'XTick',0.0:0.05:25,...
    'YTickLabel',{'','0.5','1.0','1.5','2.0'},...
    'YTick',0.0:0.5:2,...
    'LineWidth', 3);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0 0.25]);
ylim(subplot2,[0. 2]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');
legend('off')
% create plot of hx 2p
plot2(1) = plot(x_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.020');
% create plot of hx 4p
plot2(2) = plot(x_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.035');
% create plot of hx 6p
plot2(3) = plot(x_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' \it S \rm = 0.055');



% create plot of hx 2p with bedload
plot(the_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName',' S = 0.02');

% create plot of hx 4p with bedload
plot(the_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName',' S = 0.035');

% create plot of hx 6p with bedload
plot(the_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

% regression curve - confidence
plot(xInterp_bIx,yInterp_bIx,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName',' S = 0.02');

% regression curve 
plot(xInterp_bIx,yInterp_bIx,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');

fMakeXgrid(0.05:0.05:0.20,[0,2],0.5);
fMakeYgrid([0,0.25],0.5:0.5:2,0.5);

% Create xlabel
xlabel('Slope-corrected contraction width\it b_{*}\cdot S\rm [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
ylabel('Relative upstream water depth\it h_{*}\rm [-]',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');  
annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');
% create legend here
lgnd = legend(plot2);
set(lgnd,'Location','SouthEast','LineWidth',1);


if write2disc
    cd('figures');
    export_fig bxhx.png -png
    export_fig bxhx.eps -eps
    export_fig bxhx.pdf -pdf
    cd ..
    disp('Figure (bxhx) written to disc (figures folder).');
    close all;
end

