function[] = fPlot_cKQbx(x_a, x_b, the_a, the_b, xInterp_2, ...
                xInterp_4, xInterp_6, xInterp_b, ...
                y_246,y_b, yInterp_2, yInterp_4, yInterp_6, yInterp_b,...
                write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 18;
MarkerS = 8;
xPos = 0.17; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);

colors=zeros(size(colors));
colors(7,:)=[0 0 0];
color_conf =[0 0 0 0.35];
lWidth_conf = 19;
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
mStyles_b = {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3)/3.5 scrsz(4)]);


%% SUBPLOT a) -- vertical
subplot1 = subplot(2,1,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.1','0.2','0.3','0.4','0.5'},...
    'YTick',0.0:0.1:.5, ...
    'LineWidth', 1.5);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 5]);
ylim(subplot1,[0. .5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of hx 2p
plot1(1) = plot(x_a(:,1),y_246(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.020');

% create plot of hx 4p
plot1(2) = plot(x_a(:,2),y_246(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.035');
% create plot of hx 6p
plot1(3) = plot(x_a(:,3),y_246(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

% create legend here
lgnd = legend(subplot1,'show');
set(lgnd,'Location','SouthEast','LineWidth',0.75);

% create plot of hx 2p + Qb
plot1(4) = plot(the_a(:,1),y_246(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.020 (free surface flow)');

% create plot of hx 4p + Qb
plot1(5) = plot(the_a(:,2),y_246(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.035 (free surface flow)');
% create plot of hx 6p + Qb
plot1(6) = plot(the_a(:,3),y_246(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.055 (free surface flow)');

% regression curve - confidence
plot1(7) = plot(xInterp_2,yInterp_2,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-10,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');
plot1(8) = plot(xInterp_4,yInterp_4,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-12,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');
plot1(9) = plot(xInterp_6,yInterp_6,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-11,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curves
plot1(10) = plot(xInterp_2,yInterp_2,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');
plot1(11) = plot(xInterp_4,yInterp_4,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');
plot1(12) = plot(xInterp_6,yInterp_6,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');

% LINE UP
fMakeXgrid(1:1:4,[0,0.5],0.5);
fMakeYgrid([0,5],0.1:0.1:0.4,0.5);
% Create xlabel
xlabel('Relative contraction width b_* [-]',...
    'FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
tt = '\mbox{Discharge coefficient} C$_{new}$ [-]';
ylabel(tt,...
    'Interpreter','LaTex',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');
% ylabel('Discharge coefficient $C$ [-]',...
%     'FontSize',fontS,...
%     'FontName','TimesNewRoman');
annotation(figure1,'textbox',...
        [xPos 0.815  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');
    
% % indicate reg. curve equations
% ylimG=get(gca,'ylim');
% xlimG=get(gca,'xlim');
% text(xlimG(2)-0.965,ylimG(2)-0.14,['C(0.020) = 0.63 h_* - 0.17',...
%     char(10),'C(0.035) = 0.49 h_* - 0.13',...
%     char(10),'C(0.055) = 0.37 h_* - 0.09'],...
%     'FontName','TimesNewRoman','FontSize',fontS,...
%     'BackgroundColor',[1 1 1])


%% SUBPLOT b) -- lateral
subplot2 = subplot(2,1,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','TimesNewRoman','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:.2:1, ...
    'LineWidth', 1.5);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 0.15]);
ylim(subplot2,[0. 1]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of hx 2p
plot2(1) = plot(x_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.020');

% create plot of hx 4p
plot2(2) = plot(x_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.035');
% create plot of hx 6p
plot2(3) = plot(x_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

% create legend here
lgnd = legend(subplot2,'show');
set(lgnd,'Location','SouthEast','LineWidth',0.75);

% create plot of hx 2p + Qb
plot2(4) = plot(the_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.020 (free surface flow)');

% create plot of hx 4p + Qb
plot2(5) = plot(the_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.035 (free surface flow)');
% create plot of hx 6p + Qb
plot2(6) = plot(the_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.055 (free surface flow)');

% regression curve - confidence
plot2(7) = plot(xInterp_b,yInterp_b,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curves
plot2(8) = plot(xInterp_b,yInterp_b,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');

% LINE UP
fMakeXgrid(0.03:0.03:0.12,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);

% Create xlabel
xlabel('Slope-corrected relative contraction width b_* [-]','FontSize',fontS,'FontName','TimesNewRoman');
% Create ylabel
tt = 'C''$_{new} [-]';
ylabel(tt,...
    'Interpreter','LaTex',...
    'FontSize',fontS,...
    'FontName','TimesNewRoman');  
annotation(figure1,'textbox',...
        [xPos 0.34  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','TimesNewRoman','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');
% annotation(figure1,'textbox',...
%         [xPos+0.5 0.34  0.4 0.1],... % [x_begin y_begin length height]
%         'String',{'f_{i} = 0.25'},...
%         'FontName','TimesNewRoman','FontSize',fontS,...
%         'FitBoxToText','on',...
%         'BackgroundColor',[1 1 1],...
%         'LineStyle','-');

% ylimG=get(gca,'ylim');
% xlimG=get(gca,'xlim');
% text(xlimG(2)-0.6,ylimG(2)-0.1,'C'' = h_* - 0.29',...
%     'FontName','TimesNewRoman','FontSize',fontS,...
%     'BackgroundColor',[1 1 1])

%% WRITING

if write2disc
    cd('figures');
    export_fig cKQbx.png -png
    export_fig cKQbx.eps -eps
    cd ..
    disp('Figure (cKQbx) written to disc (figures folder).');
    close all;
end

