function [ ] = fPlotZ( Xdata, Ydata, fontS, Q )
% Plots points of Xdata COLUMNS against Ydata COLUMNS
% nTitle = figure title name
% nData = data names for legend entries

nC = numel(Ydata(1,:));

scrsz = get(0,'ScreenSize');
figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)]);
%mStyles = {'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
colors = colormap(copper(nC));
% Create axes
%     'YTickLabel',{' ','509','510','511','512','513','514','515','516',...
%     '517','518','519','520'}, 'YTick',[510 511 512 ...
%     513 514 515 516 517 518 519 520],...
%     'XTickLabel',{'5+850','5+800','5+750','5+700','5+650','5+600',...
%           '5+550','5+500','5+450','5+400','5+350','5+300'},...
%     'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1],...
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XGrid','on',...
    'XColor',[0 0 0],...
    'LineWidth',1,...
    'GridLineStyle','-',...
    'FontSize',fontS,...
    'FontName','Arial');
%xlim(axes1,[10 40]);
%ylim(axes1,[508 520]);
box(axes1,'on');
hold(axes1,'all');

for i = 1:nC
    plot1(i) = plot(Xdata(:,i),Ydata(:,i),'Parent',axes1,...
        'LineStyle','-',...
        'Color',colors(i,:));
    hold on
    set(plot1(i),'DisplayName',['Q = ',num2str(Q(i)*10^3,'%0.2f'), 'l/s']);
end

xlabel('Local losses by roughness \zeta_r [-]','FontSize',fontS,...
    'FontName','Arial');
ylabel('Standard deviation (single sections) \sigma [-]',...
    'FontSize',fontS,'FontName','Arial');
%title({nTitle},'FontSize',fontS,'FontName','Times New Roman','FontAngle','italic');
legend1 = legend(axes1,'show');
set(legend1,'Location','EastOutside','FontSize',fontS-3);
export_fig(['std_zeta','.png'], '-png')
close all;

% CREATE TEXTBOXES --------------------------------------------------------
% subFont=10;
% annotation(figure1,'textbox',...
%     [0.33 0.13 0.27 0.08],...
%     'String',{'FDS/FDP = Fosse Dissipation Standard/Poire', ...
%               'PS/PM = Pilier central Standard/Mince',...
%               'OO/OF = Orifice Ouvert/Fermé'},...
%     'FontWeight','light',...
%     'FontSize',fontS-subFont,...
%     'FontName','Arial',...
%     'FontAngle','oblique',...
%     'FitBoxToText','off',...
%     'LineStyle','-',...
%     'BackgroundColor',[1 1 1],...
%     'Color',[0.15 0.15 0.15]);


end



