function[] = fPlot_cFr0(x_b, the_b, xInterp_2, xInterp_4, xInterp_6, xInterp_b, ...
                y_246,y_b, yInterp_2, yInterp_4, yInterp_6, yInterp_b, write2disc)
% Y = matrix with 3 columns

scrsz = get(0,'ScreenSize');
% scrsz =   1 1 1920 1200
%scrsz(4) = scrsz(4)*4;
fontS = 28;
MarkerS = 12;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);

colors=zeros(size(colors));
colors(7,:)=[0 0 0];
color_conf =[0 0 0 0.35];
lWidth_conf = 19;
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
mStyles_b = {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);


%% SUBPLOT a) -- vertical
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.1','0.2','0.3','0.4','0.5'},...
    'YTick',0.0:0.1:.5, ...
    'LineWidth', 1.5);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 1]);
ylim(subplot1,[0. .5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of Fr0 2p
plot1(1) = plot(x_b(:,1),y_246(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.020');

% create plot of Fr0 4p
plot1(2) = plot(x_b(:,2),y_246(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.035');
% create plot of Fr0 6p
plot1(3) = plot(x_b(:,3),y_246(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

% create legend here
lgnd = legend(subplot1,'show');
set(lgnd,'Location','West','LineWidth',0.75);

% create plot of Fr0 2p + Qb
plot1(4) = plot(the_b(:,1),y_246(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.020 (free surface flow)');

% create plot of Fr0 4p + Qb
plot1(5) = plot(the_b(:,2),y_246(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.035 (free surface flow)');
% create plot of Fr0 6p + Qb
plot1(6) = plot(the_b(:,3),y_246(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.055 (free surface flow)');

% regression curve - confidence
plot1(7) = plot(xInterp_2,yInterp_2,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-10,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');
plot1(8) = plot(xInterp_4,yInterp_4,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-12,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');
plot1(9) = plot(xInterp_6,yInterp_6,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-11,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curves
plot1(10) = plot(xInterp_2,yInterp_2,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');
plot1(11) = plot(xInterp_4,yInterp_4,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');
plot1(12) = plot(xInterp_6,yInterp_6,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');

% LINE UP
fMakeXgrid(0.2:0.2:0.8,[0,0.5],0.5);
fMakeYgrid([0,1],0.1:0.1:0.4,0.5);
% Create xlabel
xlabel('Upstream Froude numer Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
tt = '\mbox{Discharge coefficient} C [-]';
ylabel(tt,...
    'Interpreter','LaTex',...
    'FontSize',fontS,...
    'FontName','Arial');

annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...        
        'LineStyle','none');

%% SUBPLOT b) -- lateral
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:.2:1, ...
    'LineWidth', 1.5);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 1]);
ylim(subplot2,[0. 1]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');

% create plot of Fr0 2p
plot2(1) = plot(x_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.020');

% create plot of Fr0 4p
plot2(2) = plot(x_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.035');
% create plot of Fr0 6p
plot2(3) = plot(x_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S = 0.055');

% create legend here
lgnd = legend(subplot2,'show');
set(lgnd,'Location','West','LineWidth',0.75);

% create plot of Fr0 2p + Qb
plot2(4) = plot(the_b(:,1),y_b(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.020 (free surface flow)');

% create plot of Fr0 4p + Qb
plot2(5) = plot(the_b(:,2),y_b(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.035 (free surface flow)');
% create plot of Fr0 6p + Qb
plot2(6) = plot(the_b(:,3),y_b(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','I = 0.055 (free surface flow)');

% regression curve - confidence
plot2(7) = plot(xInterp_b,yInterp_b,...
    'Color',color_conf,...
    'LineWidth',lWidth_conf-5,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Confidence interval');

% regression curves
plot2(8) = plot(xInterp_b,yInterp_b,...
    'Color',[0 0 0],...
    'LineWidth',1,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},...
    'DisplayName','Regression curve');

% LINE UP
fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);

% Create xlabel
xlabel('Upstream Froude numer Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
tt = 'C'' = 1.25 $\frac{ 0.25\cdot S-C}{S - 1}$ [-]';
ylabel(tt,...
    'Interpreter','LaTex',...
    'FontSize',fontS,...
    'FontName','Arial');  
annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'BackgroundColor',[1 1 1],...
        'LineStyle','none');
% annotation(figure1,'textbox',...
%         [xPos+0.5 0.34  0.4 0.1],... % [x_begin y_begin length height]
%         'String',{'f_{i} = 0.25'},...
%         'FontName','Arial','FontSize',fontS,...
%         'FitBoxToText','on',...
%         'BackgroundColor',[1 1 1],...
%         'LineStyle','-');

%% WRITING

if write2disc
    cd('figures');
    export_fig cFr0.png -png
    export_fig cFr0.eps -eps
    cd ..
    disp('Figure (cFr0) written to disc (figures folder).');
    close all;
end

