function[] = fPlot_mupFr0(x_a, x_b, x_c, the_a, the_b, the_c, ...
            y_b1, y_b2, y_b3, ...
            xInterp, lyInterp_a, yInterp_a, uyInterp_a, ...
            lyInterp_b, yInterp_b, uyInterp_b, write2disc)

scrsz =   [1 1 1920 1200];
fontS = 28;
MarkerS = 18;
yPos = 0.82; % y position of the textbox
% create gray scale colormap
cmap = contrast(ones(1,10));
colors = colormap(cmap);
colors=zeros(size(colors));
colors(7,:)=[0 0 0];
mColorLat = [0. 0. 0.];
limColor = [.5 .5 .5];
%other:{'+','o','diamond','v','square','pentagram','x','^','*','>','h','<'};
mStyles = {'o','square','v','none'};
mStyles_b = {'o','square','v','none'}; % former: {'h','diamond','^','none'};
lStyles = {'none','-','-.'};

figure1 = figure('Color',[1 1 1],'Position',[1 scrsz(4) scrsz(3) scrsz(4)/1.6]);

%% SUBPLOT a) -- vertical
subplot1 = subplot(1,2,1,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.25','0.50','0.75','1.00','1.25','1.50'},...
    'YTick',0.0:0.25:1.5,...
    'LineWidth', 3);
hold(subplot1,'all');
box(subplot1,'on');
grid(subplot1,'off');

xlim(subplot1,[0. 1]);
ylim(subplot1,[0. 1.5]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot1,'Layer','top','Clipping','on','ClippingStyle','rectangle');

%% LAT without Qb (for legend) 

% create plot of mu 2p-lat
plot1(1) = plot(x_b(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S_0 = 0.020');

% create plot of mu 4p-lat
plot1(numel(plot1)+1) = plot(x_b(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S_0 = 0.035');

% create plot of mu 6p-lat
plot1(numel(plot1)+1) = plot(x_b(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName',' S_0 = 0.055');

% create legend here
lgnd = legend(subplot1,'show');
set(lgnd,'Location','SouthEast','LineWidth',1);

%% LAT with Qb

% create plot of mu 2p-lat
plot1(numel(plot1)+1) = plot(the_b(:,1),y_b2(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface');

% create plot of mu 4p-lat
plot1(numel(plot1)+1) = plot(the_b(:,2),y_b2(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.035)');

% create plot of mu 6p-lat
plot1(numel(plot1)+1) = plot(the_b(:,3),y_b2(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles_b{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',mColorLat+0.502,...
    'MarkerEdgeColor', mColorLat, ...
    'DisplayName','Free surface (I = 0.055)');

%% REGRESSION CURVES
plot1(numel(plot1)+1) = plot(xInterp,lyInterp_a,... % confidence lower
    'Color',limColor,...
    'LineWidth',1.5,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
plot1(numel(plot1)+1) = plot(xInterp,yInterp_a,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');
plot1(numel(plot1)+1) = plot(xInterp,uyInterp_a,... % confidence upper
    'Color',limColor,...
    'LineWidth',1.5,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');

% LINE UP
fMakeXgrid(0.2:0.2:0.8,[0,1.5],0.5);
fMakeYgrid([0,1],0.25:0.25:1.25,0.5);

% Create xlabel
xlabel('Upstream Froude number Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Discharge coefficient (free surface) \mu_f [-]',...
    'FontSize',fontS,...
    'FontName','Arial');  
annotation(figure1,'textbox',...
        [0.14 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'a)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

%% SUBPLOT b) SLOPE CORRECTION
subplot2 = subplot(1,2,2,'Parent',figure1,'FontSize',fontS,...
    'FontName','Arial','GridLineStyle','-',...
    'XTickLabel',{'0.0','0.2','0.4','0.6','0.8','1.0'},...
    'XTick',0.0:0.2:1,...
    'YTickLabel',{'','0.2','0.4','0.6','0.8','1.0'},...
    'YTick',0.0:0.2:1,...
    'LineWidth', 3);
hold(subplot2,'all');
box(subplot2,'on');
grid(subplot2,'off');

xlim(subplot2,[0. 1]);
ylim(subplot2,[0. 1]);

% cut (clip) lines outside of axis !! does not work for markers!
set(subplot2,'Layer','top','Clipping','on','ClippingStyle','rectangle');

%% VERT + LAT without Qb (for legend) 
% create plot of mu 2p-vert
plot2(1) = plot(x_a(:,1),y_b1(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName',' S_0 = 0.020');

% create plot of mu 4p-vert
plot2(numel(plot2)+1) = plot(x_a(:,2),y_b1(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName',' S_0 = 0.035');

% create plot of mu 6p-vert
plot2(numel(plot2)+1) = plot(x_a(:,3),y_b1(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName',' S_0 = 0.055');

% create legend here
lgnd = legend(subplot2,'show');
set(lgnd,'Location','SouthEast','LineWidth',1);
%% COMBINED without Qb 

% create plot of mu 2p-comb
plot2(numel(plot2)+1) = plot(x_c(:,1),y_b3(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'DisplayName','Pressurized');

% create plot of mu 4p-comb
plot2(numel(plot2)+1) = plot(x_c(:,2),y_b3(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'DisplayName','Pressurized');

% create plot of mu 6p-comb
plot2(numel(plot2)+1) = plot(x_c(:,3),y_b3(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'DisplayName','Pressurized');

%% VERT + LAT with Qb 
% create plot of mu 2p-vert
plot2(numel(plot2)+1) = plot(the_a(:,1),y_b1(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized (I = 0.020)');

% create plot of mu 4p-vert
plot2(numel(plot2)+1) = plot(the_a(:,2),y_b1(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized (I = 0.035)');

% create plot of mu 6p-vert
plot2(numel(plot2)+1) = plot(the_a(:,3),y_b1(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized (I = 0.055)');

%% COMBINED with Qb

% create plot of mu 2p-comb
plot2(numel(plot2)+1) = plot(the_c(:,1),y_b3(:,1),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,3},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized');

% create plot of mu 4p-comb
plot2(numel(plot2)+1) = plot(the_c(:,2),y_b3(:,2),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,2},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized');

% create plot of mu 6p-comb
plot2(numel(plot2)+1) = plot(the_c(:,3),y_b3(:,3),...
    'Color',colors(7,:),...
    'LineWidth',1,'LineStyle',lStyles{1,1},...
    'Marker',mStyles{1,1},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Pressurized');

%% REGRESSION CURVES
plot2(numel(plot2)+1) = plot(xInterp,lyInterp_b,... % confidence lower
    'Color',limColor,...
    'LineWidth',1.5,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Lower');
plot2(numel(plot2)+1) = plot(xInterp,yInterp_b,...
    'Color',colors(7,:),...
    'LineWidth',3,'LineStyle',lStyles{1,2},...
    'Marker',mStyles{1,4},'MarkerSize',MarkerS,...
    'MarkerFaceColor',[0.502 0.502 0.502],...
    'DisplayName','Interpolation curve 2p');
plot2(numel(plot2)+1) = plot(xInterp,uyInterp_b,... % confidence upper
    'Color',limColor,...
    'LineWidth',1.5,'LineStyle',lStyles{1,3},...
    'Marker',mStyles{1,4},...
    'DisplayName','Upper');


%% LINE UP
fMakeXgrid(0.2:0.2:0.8,[0,1],0.5);
fMakeYgrid([0,1],0.2:0.2:0.8,0.5);

% Create xlabel
xlabel('Upstream Froude number Fr_0 [-]','FontSize',fontS,'FontName','Arial');
% Create ylabel
ylabel('Discharge coefficient (pressurized) \mu_p [-]',...
    'FontSize',fontS,...
    'FontName','Arial');  

annotation(figure1,'textbox',...
        [0.585 yPos  0.4 0.1],... % [x_begin y_begin length height]
        'String',{'b)'},...
        'FontName','Arial','FontSize',fontS+2,...
        'FontWeight','bold',...
        'FitBoxToText','on',...
        'LineStyle','none');

if write2disc
    cd('figures');
    export_fig appMuFr0.png -png
    export_fig appMuFr0.eps -eps
    cd ..
    disp('Figure (muFr0) written to disc (figures folder).');
    close all;
end

